version: "3.9"

services:
  devtree-api:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - .env
    command: npm run dev
  devtree-api-test:
    build: .
    env_file:
      - .env
    command: npm run test